networks:
  proxy:
    external: true

services:
  app:
    image: node:22
    container_name: web.${APP_NAME}
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ./infra/install.sh
    ports:
      - "3000:5173"
    networks:
      - proxy